require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/decks", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Deck. As you add validations to Deck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Deck.create! valid_attributes
      get decks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      deck = Deck.create! valid_attributes
      get deck_url(deck)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_deck_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      deck = Deck.create! valid_attributes
      get edit_deck_url(deck)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Deck" do
        expect {
          post decks_url, params: { deck: valid_attributes }
        }.to change(Deck, :count).by(1)
      end

      it "redirects to the created deck" do
        post decks_url, params: { deck: valid_attributes }
        expect(response).to redirect_to(deck_url(Deck.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Deck" do
        expect {
          post decks_url, params: { deck: invalid_attributes }
        }.to change(Deck, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post decks_url, params: { deck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested deck" do
        deck = Deck.create! valid_attributes
        patch deck_url(deck), params: { deck: new_attributes }
        deck.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the deck" do
        deck = Deck.create! valid_attributes
        patch deck_url(deck), params: { deck: new_attributes }
        deck.reload
        expect(response).to redirect_to(deck_url(deck))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        deck = Deck.create! valid_attributes
        patch deck_url(deck), params: { deck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested deck" do
      deck = Deck.create! valid_attributes
      expect {
        delete deck_url(deck)
      }.to change(Deck, :count).by(-1)
    end

    it "redirects to the decks list" do
      deck = Deck.create! valid_attributes
      delete deck_url(deck)
      expect(response).to redirect_to(decks_url)
    end
  end
end
